// Generated by CoffeeScript 1.8.0
var __modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

registerDirective('inventoryElements', {
  restrict: 'E',
  template: '<div ng-if="elements.length">' + '<h4>{{inventory.name}}</h4>' + '<span>Sort by: </span>' + '<div class="btn-group">' + '<button class="btn btn-default btn-sm navbar-btn" ng-click="sort(\'type\')" ng-class="{\'active\': sorting === \'type\'}"><span class="fa fa-send-o" > Element type</span></button>' + '<button class="btn btn-default btn-sm navbar-btn" ng-click="sort(\'IA\')" ng-class="{\'active\': sorting === \'IA\'}"><span class="fa fa-cubes"> Inventory type</span></button>' + '<button class="btn btn-default btn-sm navbar-btn" ng-click="sort(\'status\')" ng-class="{\'active\': sorting === \'status\'}"><span class="fa fa-list"> Inventory state</span></button>' + '</div>' + '<div class="list-group">' + '<a href="{{URLconfig.element}}/{{element.id}}" ng-repeat="element in elements | orderBy:sorting:sortingOrder" class="list-group-item">' + '<span ng-if="element.status" class="badge" ng-class="{\'badge-info\': !element.status, \'badge-danger\': (element.status === \'notfound\'), \'badge-warning\': (element.status === \'missplaced\'), \'badge-success\': (element.status === \'placed\')}">{{element.status}}</span>' + '{{element.name}}' + '</a>' + '</div>' + '</div>',
  controller: function($scope, $rootScope, $http, $q) {
    var getElements, mockElements, setElements, urlBase;
    urlBase = 'https://edocu.service.dev.edocu.local';
    $scope.sorting = 'status';
    $scope.sortingOrder = true;
    mockElements = function(id) {
      var another, one;
      one = [
        {
          id: 1,
          name: 'biela stolicka',
          type: 'Chair',
          status: 'placed',
          IA: 'Furniture'
        }, {
          id: 2,
          name: 'stolicka otocneho druhu',
          type: 'Chair',
          status: 'placed',
          IA: 'Furniture'
        }, {
          id: 3,
          name: 'stol velky',
          type: 'Table',
          IA: 'Furniture'
        }, {
          id: 4,
          name: 'zelena stolicka',
          type: 'Chair',
          status: 'placed',
          IA: 'Furniture'
        }, {
          id: 5,
          name: 'biela stolicka',
          type: 'Chair',
          IA: 'Furniture'
        }, {
          id: 6,
          name: 'vitrina',
          type: 'Cabinet',
          IA: 'Furniture'
        }, {
          id: 7,
          name: 'modra stolicka',
          type: 'Chair',
          IA: 'Furniture'
        }, {
          id: 8,
          name: 'skrina',
          type: 'Cabinet',
          status: 'placed',
          IA: 'Furniture'
        }, {
          id: 9,
          name: 'stolicka otocneho druhu',
          type: 'Chair',
          IA: 'Furniture'
        }
      ];
      another = [
        {
          id: 10,
          name: 'tablet 9',
          type: 'Tablet',
          status: 'placed',
          IA: 'Computing technology'
        }, {
          id: 11,
          name: 'Lenovo IdeaPad 123',
          type: 'Notebook',
          status: 'missplaced',
          IA: 'Computing technology'
        }, {
          id: 12,
          name: 'vedecky kalkulator 3000',
          type: 'Calculator',
          status: 'notfound',
          IA: 'Computing technology'
        }, {
          id: 13,
          name: 'Charger',
          type: 'Electronics',
          status: 'notfound',
          IA: 'Other Electronics'
        }, {
          id: 14,
          name: 'Headphones',
          type: 'Speakers',
          status: 'missplaced',
          IA: 'Other Electronics'
        }, {
          id: 15,
          name: 'tablet Nexus 9',
          type: 'Tablet',
          status: 'missplaced',
          IA: 'Computing technology'
        }, {
          id: 16,
          name: 'TV 32',
          type: 'Television',
          status: 'placed',
          IA: 'Other Electronics'
        }, {
          id: 17,
          name: 'Lenovo IdeaPad 124',
          type: 'Notebook',
          status: 'placed',
          IA: 'Computing technology'
        }, {
          id: 18,
          name: 'Desktop lamp',
          type: 'Electronics',
          status: 'placed',
          IA: 'Other Electronics'
        }
      ];
      if (__modulo(id, 2) === 0) {
        return one;
      } else {
        return another;
      }
    };
    getElements = function() {
      var defer;
      defer = $q.defer();
      $http.get(urlBase + '/service/inventory/getElements/', options).success(function(response) {
        return defer.resolve(response);
      }).error(function() {
        return defer.resolve(false);
      });
      return defer.promise;
    };
    setElements = function(elements) {
      $scope.$apply(function() {
        $scope.elements = elements;
      });
    };
    $rootScope.$on('inventory.selected', function(event, inventory) {
      $scope.$apply(function() {
        $scope.inventory = inventory;
      });
      setElements(mockElements(inventory.id));
    });
    $scope.sort = function(sortBy) {
      if ($scope.sorting === sortBy) {
        return $scope.sortingOrder = !$scope.sortingOrder;
      } else {
        return $scope.sorting = sortBy;
      }
    };
  }
});
